export enum TransactionStatus {
    PENDING = "PENDING",
    COMPLETE = "COMPLETE",
    FAILED = "FAILED"
}
export enum BridgeType {
    PACTUS_POLYGON = "PACTUS_POLYGON",
    POLYGON_PACTUS = "POLYGON_PACTUS",
    BSC_PACTUS = "BSC_PACTUS",
    PACTUS_BSC = "PACTUS_BSC",
    BASE_PACTUS = "BASE_PACTUS",
    PACTUS_BASE = "PACTUS_BASE",
}